# Generated by Django 3.1.4 on 2020-12-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('famale', 'famale')], default='male', max_length=10)),
                ('province', models.CharField(max_length=200)),
                ('national_id', models.CharField(max_length=100, unique=True)),
                ('current_address', models.CharField(max_length=500)),
                ('hostel', models.BooleanField(default=False)),
                ('budget', models.BooleanField(default=False)),
                ('semester', models.CharField(choices=[('', 'choose...'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=10)),
                ('image', models.ImageField(upload_to='students/')),
            ],
        ),
    ]
