# Generated by Django 3.1.4 on 2020-12-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='students/files')),
            ],
        ),
    ]
